id: I825A5F55
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:15:40+00:00'
last_modified: '2022-06-16T04:34:56.264052+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9297
  title: བཀའ་གདམས་རིན་པོ་ཆེའི་ཆོས་འབྱུང་རྣམ་ཐར་ཉིན་མོར་བྱེད་པའི་འོད་སྟོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    80F0:
      image_group_id: I4PD4421
      title: Volume 1 of phyag rgya chen po'i sgros 'bum/
      total_pages: 286
      order: 1
      base_file: 80F0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
